[orcalab]
pak_urls = [ "https://orcalab-open.oss-cn-shanghai.aliyuncs.com/orcalab_pc.26.2.1.3.pak",]
python_project_url = "https://orcalab-open.oss-cn-shanghai.aliyuncs.com/python-project_pc.26.2.1.3.tar.xz"
version = "26.2.1.3"
