[orcalab]
pak_urls = [ "https://orcalab-open.oss-cn-shanghai.aliyuncs.com/orcalab_linux.26.1.9.2.pak",]
python_project_url = "https://orcalab-open.oss-cn-shanghai.aliyuncs.com/python-project_linux.26.1.9.2.tar.xz"
version = "26.1.9.2"
